{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyPmaSu2p6ZVdV8krE77xKPQ"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":3,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"YtT9l0zrb7Oo","executionInfo":{"status":"ok","timestamp":1714658065727,"user_tz":-60,"elapsed":2066,"user":{"displayName":"Liz","userId":"09230529501155873954"}},"outputId":"dbfd96ac-5790-447f-f870-4e255e5ddc49"},"outputs":[{"output_type":"stream","name":"stdout","text":["Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n"]}],"source":["import os, sys\n","from google.colab import drive\n","drive.mount('/content/drive')\n","\n","my_path = '/content/package'\n","save_path = '/content/drive/My\\ Drive/LLM/sandbox'\n","\n","#os.symlink(save_path, my_path)\n","sys.path.insert(0, my_path)"]},{"cell_type":"code","source":["!pip install --target=$my_path pymongo\n","!pip install --target=$my_path praw\n","!pip install --target=$my_path langchain_core\n","!pip install --target=$my_path langchain_openai\n","!pip install --target=$my_path langchain_mongodb\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":1000},"id":"Bq_AH_T-cP4b","outputId":"4435edbf-f150-45b7-c546-f3fd701d3b0f"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting pymongo\n","  Using cached pymongo-4.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (669 kB)\n","Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)\n","  Using cached dnspython-2.6.1-py3-none-any.whl (307 kB)\n","Installing collected packages: dnspython, pymongo\n","Successfully installed dnspython-2.6.1 pymongo-4.7.1\n","\u001b[31mERROR: Exception:\n","Traceback (most recent call last):\n","  File \"/usr/lib/python3.10/shutil.py\", line 816, in move\n","    os.rename(src, real_dst)\n","FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-target-40bblv9p/lib/python/bson' -> '/content/package/bson'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 169, in exc_logging_wrapper\n","    status = run_func(*args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py\", line 242, in wrapper\n","    return func(self, options, args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 507, in run\n","    self._handle_target_dir(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 566, in _handle_target_dir\n","    shutil.move(os.path.join(lib_dir, item), target_item_dir)\n","  File \"/usr/lib/python3.10/shutil.py\", line 832, in move\n","    copytree(src, real_dst, copy_function=copy_function,\n","  File \"/usr/lib/python3.10/shutil.py\", line 559, in copytree\n","    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,\n","  File \"/usr/lib/python3.10/shutil.py\", line 457, in _copytree\n","    os.makedirs(dst, exist_ok=dirs_exist_ok)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","FileNotFoundError: [Errno 2] No such file or directory: '/content/package/bson'\u001b[0m\u001b[31m\n","\u001b[0mCollecting praw\n","  Using cached praw-7.7.1-py3-none-any.whl (191 kB)\n","Collecting prawcore<3,>=2.1 (from praw)\n","  Using cached prawcore-2.4.0-py3-none-any.whl (17 kB)\n","Collecting update-checker>=0.18 (from praw)\n","  Using cached update_checker-0.18.0-py3-none-any.whl (7.0 kB)\n","Collecting websocket-client>=0.54.0 (from praw)\n","  Using cached websocket_client-1.8.0-py3-none-any.whl (58 kB)\n","Collecting requests<3.0,>=2.6.0 (from prawcore<3,>=2.1->praw)\n","  Using cached requests-2.31.0-py3-none-any.whl (62 kB)\n","Collecting charset-normalizer<4,>=2 (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw)\n","  Using cached charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)\n","Collecting idna<4,>=2.5 (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw)\n","  Using cached idna-3.7-py3-none-any.whl (66 kB)\n","Collecting urllib3<3,>=1.21.1 (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw)\n","  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)\n","Collecting certifi>=2017.4.17 (from requests<3.0,>=2.6.0->prawcore<3,>=2.1->praw)\n","  Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)\n","Installing collected packages: websocket-client, urllib3, idna, charset-normalizer, certifi, requests, update-checker, prawcore, praw\n","Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 praw-7.7.1 prawcore-2.4.0 requests-2.31.0 update-checker-0.18.0 urllib3-2.2.1 websocket-client-1.8.0\n","\u001b[31mERROR: Exception:\n","Traceback (most recent call last):\n","  File \"/usr/lib/python3.10/shutil.py\", line 816, in move\n","    os.rename(src, real_dst)\n","FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-target-fcn_s5xc/lib/python/urllib3-2.2.1.dist-info' -> '/content/package/urllib3-2.2.1.dist-info'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py\", line 169, in exc_logging_wrapper\n","    status = run_func(*args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py\", line 242, in wrapper\n","    return func(self, options, args)\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 507, in run\n","    self._handle_target_dir(\n","  File \"/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py\", line 566, in _handle_target_dir\n","    shutil.move(os.path.join(lib_dir, item), target_item_dir)\n","  File \"/usr/lib/python3.10/shutil.py\", line 832, in move\n","    copytree(src, real_dst, copy_function=copy_function,\n","  File \"/usr/lib/python3.10/shutil.py\", line 559, in copytree\n","    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,\n","  File \"/usr/lib/python3.10/shutil.py\", line 457, in _copytree\n","    os.makedirs(dst, exist_ok=dirs_exist_ok)\n","  File \"/usr/lib/python3.10/os.py\", line 225, in makedirs\n","    mkdir(name, mode)\n","FileNotFoundError: [Errno 2] No such file or directory: '/content/package/urllib3-2.2.1.dist-info'\u001b[0m\u001b[31m\n","\u001b[0m"]},{"output_type":"display_data","data":{"application/vnd.colab-display-data+json":{"pip_warning":{"packages":["certifi"]},"id":"9cb999f11d304e9dad889e1ca17e698d"}},"metadata":{}},{"output_type":"stream","name":"stdout","text":["Collecting langchain_core\n","  Using cached langchain_core-0.1.48-py3-none-any.whl (302 kB)\n","Collecting PyYAML>=5.3 (from langchain_core)\n","  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)\n","Collecting jsonpatch<2.0,>=1.33 (from langchain_core)\n","  Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)\n","Collecting langsmith<0.2.0,>=0.1.0 (from langchain_core)\n","  Using cached langsmith-0.1.52-py3-none-any.whl (116 kB)\n","Collecting packaging<24.0,>=23.2 (from langchain_core)\n","  Using cached packaging-23.2-py3-none-any.whl (53 kB)\n","Collecting pydantic<3,>=1 (from langchain_core)\n","  Using cached pydantic-2.7.1-py3-none-any.whl (409 kB)\n","Collecting tenacity<9.0.0,>=8.1.0 (from langchain_core)\n","  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)\n","Collecting jsonpointer>=1.9 (from jsonpatch<2.0,>=1.33->langchain_core)\n","  Using cached jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)\n","\u001b[31mERROR: Operation cancelled by user\u001b[0m\u001b[31m\n","\u001b[0mCollecting langchain_openai\n","  Using cached langchain_openai-0.1.5-py3-none-any.whl (34 kB)\n","Collecting langchain-core<0.2.0,>=0.1.46 (from langchain_openai)\n","  Using cached langchain_core-0.1.48-py3-none-any.whl (302 kB)\n","Collecting openai<2.0.0,>=1.10.0 (from langchain_openai)\n","  Using cached openai-1.25.0-py3-none-any.whl (312 kB)\n","Collecting tiktoken<1,>=0.5.2 (from langchain_openai)\n","  Using cached tiktoken-0.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)\n","Collecting PyYAML>=5.3 (from langchain-core<0.2.0,>=0.1.46->langchain_openai)\n","  Using cached PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)\n","Collecting jsonpatch<2.0,>=1.33 (from langchain-core<0.2.0,>=0.1.46->langchain_openai)\n","  Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)\n","Collecting langsmith<0.2.0,>=0.1.0 (from langchain-core<0.2.0,>=0.1.46->langchain_openai)\n","  Using cached langsmith-0.1.52-py3-none-any.whl (116 kB)\n","Collecting packaging<24.0,>=23.2 (from langchain-core<0.2.0,>=0.1.46->langchain_openai)\n","  Using cached packaging-23.2-py3-none-any.whl (53 kB)\n"]}]},{"cell_type":"code","source":["\n","sys.path.insert(0, my_path)"],"metadata":{"id":"2N2fZQ_3jiVn","executionInfo":{"status":"ok","timestamp":1714657629533,"user_tz":-60,"elapsed":4,"user":{"displayName":"Liz","userId":"09230529501155873954"}}},"execution_count":4,"outputs":[]},{"cell_type":"code","source":[],"metadata":{"id":"sfDnteiidJlh"},"execution_count":null,"outputs":[]}]}